### ISSUE TITLE
USER STORY: As a programmer I can design a simple website to make it easier for the user to navigate

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/book-a-table#1]
EPIC: Create the design template of the website

As a **programmer** I can **design a simple website** to **make it easier for the user to navigate**

**Acceptance Criteria**
- [x] Design the opening few pages of the website, including pub logo and favicon
- [x] Create a basic structure to the website including HTML and CSS files
- [x] Add basic content to website including header with logo and menu bar, and footer with copyright information

**Tasks**
- [x] 1: Plan the design template for the website
- [x] 2: Create opening html page
- [x] 3: Create a fixed header bar at the top to include pub logo on left side and then menu choices including Log in, Menu, What's on?, Layout, Contact pages on the right side
- [x] 4: Create footer which includes copyright information
- [x] 5: Test website opens and displays correctly
