### ISSUE TITLE
USER STORY: As a site user I receive information on future events to stay connected with the pub

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/book-a-table#11]
EPIC: <epic>

As a **site user** I can **sign up for information on future events** to **stay connected with the pub**

**Acceptance Criteria**
- [ ] Add a checkbox to allow the user to receive event emails

**Tasks**
- [ ] Add checkbox function to user profile
- [ ] Create an events page which can be sent as an email once a month to subscribed customers
- [ ] Test that events page is sent out and received
