### ISSUE TITLE
USER STORY: As a **user** I can **use the pub layout map to choose the table I want to sit at** so that I can **easily see what table suits my choice for my chosen time**

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/book-a-table#12]
EPIC: Choose table from pub layout

As a **user** I can **use the pub layout map to choose the table I want to sit at** so that I can **easily see what table suits my choice for my chosen time**

**Acceptance Criteria**
- [ ] After selecting time and date chosen, map shows available tables
- [ ] User can choose from dropdown box or something similar to choose the table for their booking
- [ ] Reserved table could be shown as being greyed out on the map and unselectable from the dropdown list

**Tasks**
- [ ] Add layout map to app
- [ ] Connect dropbox function to map
- [ ] Make reserved tables unselectable from dropdown list
- [ ] Reserved tables should be shown as being greyed out on the layout map
