### ISSUE TITLE
USER STORY: As a programmer I can create a customer database to help with the information needed when booking

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/book-a-table#3]
EPIC: Log in system for user/owner

As a **programmer** I can **create a customer database** to **help with the information needed when booking**

**Acceptance Criteria**
- [ ] Create a Log in system that also needs a password to ensure user data privacy
- [ ] Store basic customer information which both user and admin can update
- [ ] Provide limited access to user
- [ ] Enter information of upcoming events

**Tasks**
- [ ] 1: Create a Django app / directory in Django
- [ ] 2: Define and create the different models to store customer information and booking information
- [ ] 3: Set up database settings. Use PostgreSQL
- [ ] 4: Apply migrations
- [ ] 5: Create views to generate correct responses
- [ ] 6: Redesign to match website template
- [ ] 7: Apply URLs to functionalities
- [ ] 8: Define and use authentication system for customer log in
- [ ] 9: Test that these functions work
