### ISSUE TITLE
USER STORY: As a programmer I can create a customer database to store the information needed when booking

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/book-a-table#6]
EPIC: Create a database to store user information

As a **programmer** I can **create a customer database** to **store the information needed when booking**

**Acceptance Criteria**
- [ ] Create a page where the customer enters relevant contact details (mobile nr, email address etc)

**Tasks**
- [ ] 1: Style the page to make it easy for the user to navigate and enter information
- [ ] 2: Connect this page to Django
- [ ] 3: Test details can be filled in stored
