### ISSUE TITLE
USER STORY: - As a programmer I can create a mailing system to keep the user/owners update with bookings and any changes/cancellations

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/book-a-table#7]
EPIC: Mailing system

As a **programmer** I can **create a mailing system** to **keep the user/owners update with bookings and any changes/cancellations**

**Acceptance Criteria**
- [ ] Create the mailing system in EmailJS and connect it to website
- [ ] Enable the mailing system to automatically email the user once bookings have been placed or changes have been made to the booking

**Tasks**
- [ ] 1: Set up a connection with EmailJS
- [ ] 2: Connect the details to the website, including ""Contact page"" and Django contacts
- [ ] 3: Test using websites email address and users
