### ISSUE TITLE
USER STORY: As a programmer I can create sufficient checks to enable everything to run without errors

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/book-a-table#8]
EPIC: Final checks and debugging for each function

As a **programmer** I can **create sufficient checks** to **enable the website to run without errors**

**Acceptance Criteria**
- [ ] Create checks for each function

**Tasks**
- [ ] 1: Create a simple check to test the pages open properly - both indivually and linked pages
- [ ] 2: Test all website links, including pictures and social media links
- [ ] 3: Test Log in function works, user inputs updates in system
- [ ] 4: Test create new user works, user inputs updates in system
- [ ] 5: Test update information works, user inputs updates in system
- [ ] 6: Test Table booking system works, user inputs updates in system. Test booked tables are then unavailable during booked time
- [ ] 7: Test mailing system works, user inputs lead to emails to both user and owner"
- [ ] Ask two people to test the website, creating accounts and attempting to book a table, then editing their change and finally cancelling their booking to test that everything works correctly
