### ISSUE TITLE
USER STORY: As a user I can book multiple tables to make sure I can fit all my friends in

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/book-a-table#9]
EPIC: Party bookings

- As a **user** I can **book multiple tables** to **make sure I can fit all my friends in**

**Acceptance Criteria**
- [ ] All for multiple tables to be booked at once
- [ ] Include a ""Book whole floor"" option for parties

**Tasks**
- [ ] 1: Add a multiple tables function during booking
- [ ] 2: Add a ""Book whole floor"" choice during booking
- [ ] 3: Check against bookings of other tables during this time
- [ ] 4: Test that this function doesn't override other table bookings and is unavailable if there is already a table booking during the intended booking period
